### ISSUE TITLE
django 1.8 compatibility issue with 0.2.2 release

### ISSUE THREAD

**Issue by theskumar** [kaleidos/django-sampledatahelper#10]
The webdesign contrib has been removed in django 1.8, but the pypi version of 0.2.2 of this lib still make use of it. @kaleidos can we have new release please `sampledatahelper.mixins` modules doesn't seem to be present in the `master`. 

```
  File "/venv/lib/python2.7/site-packages/sampledatahelper/mixins/text_mixin.py", line 5, in <module>
    from django.contrib.webdesign import lorem_ipsum
ImportError: cannot import name lorem_ipsum
```

**Comment by euribates** [comment]
There is a simple fix, change the line in the file `sampledatahelper\mixins\text_mixin.py` from:

    from django.contrib.webdesign import lorem_ipsum

to:

    django_version = django.VERSION[0:2]
    # The lorem template tag is now included in the built-in tags
    if django_version >= (1, 8):
        from django.utils import lorem_ipsum
    else:
        from django.contrib.webdesign import lorem_ipsum

**Comment by jespino** [comment]
I split the django-sampledatahelper in a python library (sampledata) and the django-sampledatahelper, and now don't depends on django lorem_ipsum. I will test it with django 1.8 and release a new version.

Thanks!

**Comment by jespino** [comment]
Uploaded the 0.3.0 version with django 1.8 support :smile:

**Comment by theskumar** [comment]
:heart_eyes:
